# Trading Bot Configuration

# Timezone
timezone: "Europe/Kiev"

# Database
database:
  path: "data/trading_bot.db"
  warm_up_days: 90
  history_days: 270

# Binance API
binance:
  use_testnet: true  # true = использовать Binance Testnet (для теста на Replit)
  signals_only_mode: true  # true = только сигналы без торговли (не нужны API ключи)
  rest_weight_limit: 1100  # per minute
  ws_reconnect_delay: 5
  rate_limit_backoff_base: 2
  rate_limit_max_retries: 5
  orderbook_levels: 20
  snapshot_interval: 60  # seconds

# Fast Catchup - Быстрая догрузка gaps при рестарте
fast_catchup:
  enabled: true  # Включить/выключить fast catchup режим
  max_parallel: null  # null = auto (4-12 based on volume), or set manual value (1-20)
  min_gap_size: 1  # Минимальный размер gap для burst режима (в свечах)

# Periodic Gap Refill - Периодическая быстрая докачка gaps во время работы
periodic_gap_refill:
  enabled: true  # Включить/выключить периодическую докачку
  max_parallel: 8  # Максимальное количество параллельных загрузок
  lookback_minutes: 120  # Проверять gaps за последние N минут (2 часа)
  # Расписание:
  # - Каждые 15 мин → докачка 15m свечей
  # - Каждый час (XX:00) → докачка 15m + 1h свечей
  # - Каждые 4 часа (00:00, 04:00, 08:00...) → докачка 15m + 1h + 4h свечей
  # - Каждый день (00:00) → докачка 15m + 1h + 4h + 1d свечей

# Market Detection
market_detector:
  timeframes:
    signal: ["15m", "1h"]
    context: ["4h", "1d"]
    execution: ["1m"]
  
  trend:
    adx_threshold: 20
    ema_periods: [20, 50, 200]
    late_trend_atr_multiplier: 1.8
  
  range:
    adx_threshold: 20
    bb_percentile: 30
    atr_percentile: 40
  
  squeeze:
    bb_percentile: 25
    min_bars: 12

# Scoring System
scoring:
  base_threshold: 2.0
  enter_threshold: 2.0  # Threshold for entry (используется в коде как enter_threshold)
  
  volume_multiplier: 1.5
  volume_mult: 1.5  # Threshold для volume ratio (используется в коде)
  volume_score: 1
  
  cvd_score: 1
  delta_oi_score: 1
  delta_oi_threshold: [1.0, 3.0]  # [min, max] %
  delta_oi_alt_threshold: [0.5, 1.0]  # for altcoins
  doi_min_pct: 1.0  # Min OI delta % (используется в коде)
  doi_max_pct: 3.0  # Max OI delta % (используется в коде)
  
  imbalance_duration: [10, 30]  # seconds
  imbalance_score: 1
  depth_imbalance_ratio:
    long_max: 0.90  # Ratio для LONG (bid/ask < 0.90)
    short_min: 1.10  # Ratio для SHORT (bid/ask > 1.10)
  
  late_trend_penalty: -1
  funding_extreme_penalty: -1
  btc_against_penalty: -2
  btc_filter_tf: "1h"  # BTC filter timeframe

# Scanning
scanning:
  check_interval_seconds: 60  # Проверять сигналы каждые 60 секунд

# Risk Management
risk:
  risk_per_trade: 0.01  # 1% of capital
  max_daily_loss: 0.03  # 3%
  max_weekly_loss: 0.05  # 5%
  max_concurrent_positions: 10
  
  stop_loss_atr_multiplier: [0.2, 0.3]
  time_stop_bars: [6, 8]  # on 1m timeframe
  
  # Maximum stop-loss distance protection
  max_stop_distance_atr: 3.0  # Reject signals with stop > 3 ATR away
  
  rr_targets:
    breakout: [2.0, 3.0]
    retest: [1.5, 2.5]
    mean_reversion: [1.2, 2.0]

# BTC Filter
btc_filter:
  timeframe: "1h"
  impulse_threshold: 1.5  # % H1 bar range (high-low)
  impulse_cooldown: 30  # minutes
  expansion_block_mr: true
  expansion_atr_mult: 1.5  # ATR multiplier для expansion detection
  lookback_bars: 10  # Lookback period для ATR average

# Time of Day Gating
tod_gating:
  eu_session: ["07:00", "09:00"]
  us_session: ["13:30", "15:30"]
  asia_session: ["00:00", "02:00"]
  
  breakout_sessions: ["eu_session", "us_session"]
  momentum_sessions: ["eu_session", "us_session"]
  mr_sessions: ["eu_session", "us_session", "asia_session"]

# Initial Balance (ORB/IRB)
initial_balance:
  duration: 60  # minutes
  width_percentile: 30
  atr_multiplier: 0.8

# Strategy Parameters
strategies:
  enabled: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]
  
  # #1 Donchian Breakout
  donchian:
    period: 20
    timeframe: "1h"
    context_timeframe: "4h"
    min_close_distance_atr: 0.25
    volume_threshold: 1.5
  
  # #2 Squeeze Breakout
  squeeze:
    lookback: 90
    bb_percentile: 25
    min_duration: 12
    breakout_atr: 0.25
    max_distance_ema20: 1.5
  
  # #3 ORB/IRB
  orb:
    slots: ["00:00-01:00", "07:00-08:00", "13:30-14:30"]
    width_percentile: 30
    atr_multiplier: 0.8
    breakout_atr: 0.25
  
  # #4 MA/VWAP Pullback
  pullback:
    ma_periods: [20, 50]
    fib_levels: [0.382, 0.618]
    retest_atr: 0.3
    volume_threshold: 1.2
  
  # #5 Break & Retest
  retest:
    breakout_atr: 0.25
    zone_atr: [0.2, 0.3]
    volume_threshold: 1.5
    split_ratio: 0.5  # 50% limit, 50% confirm
  
  # #6 ATR Momentum
  momentum:
    impulse_atr: 1.4
    close_percentile: 20  # top 20%
    min_distance_resistance: 1.5
    pullback_ema: [9, 20]
  
  # #7 VWAP Mean Reversion
  vwap_mr:
    sigma_bands: [1, 2]
    reclaim_bars: 2
    time_stop: [6, 8]
  
  # #8 Range Fade
  range_fade:
    min_tests: 2
    time_stop: [6, 8]
  
  # #9 Volume Profile
  volume_profile:
    bin_size_percent: 0.1
    acceptance_close_atr: 0.25
    acceptance_closes: 2
  
  # #10 RSI/Stochastic MR
  oscillator_mr:
    rsi_period: 14
    stoch_period: 14
    oversold_percentile: 20
    overbought_percentile: 80
    lookback: 90
  
  # #11 Funding Arbitrage (monitoring only for MVP)
  funding:
    enabled: false
    extreme_threshold: 0.1

# Telegram
telegram:
  language: "ru"
  edit_updates: true
  compact_cards: true
  lock_per_symbol: true
  lock_ttl: 3600  # seconds

# Redis (optional - fallback to SQLite if unavailable)
redis:
  host: "localhost"
  port: 6379
  db: 0
  password: null  # Set if Redis requires authentication

# WebSocket Health
websocket:
  stale_threshold_ms: 500
  stale_warning_count: 3
  stale_window_minutes: 5
  sequence_gap_critical: true
  resync_cooldown: 120  # seconds

# Kill Switch
kill_switch:
  event_loop_lag_warning_ms: 200
  event_loop_lag_critical_ms: 400
  rss_growth_percent: 5
  rss_growth_window_minutes: 3
  recovery_green_window_minutes: 10

# Load Shedding
load_shedding:
  step1:
    disable_dom_altcoins: true
    disable_imbalance_altcoins: true
  step2:
    increase_threshold: 0.5
  step3:
    symbols_only: ["BTCUSDT", "ETHUSDT"]
  step4:
    freeze_mr_outside_slots: true

# Logging
logging:
  level: "INFO"
  console: true
  file: "logs/bot.log"
  rotation: "1 day"
  retention: "30 days"
  
  levels:
    websocket: "DEBUG"
    strategies: "INFO"
    scoring: "INFO"
    telegram: "INFO"

# Data Sources
data_sources:
  binance_vision_url: "https://data.binance.vision"
  cache_directory: "data/cache"
  incremental_update: true

# Universe
universe:
  initial_symbols: ["BTCUSDT", "ETHUSDT"]
  expand_after_stable: false
  fetch_all_pairs: true  # Fetch all USDT-M pairs from Binance
  filter_quote: "USDT"
  min_volume_24h: 10000000  # $10M minimum
  update_interval_hours: 1  # Auto-update symbol list every N hours

# Action Price Strategy (отдельная система)
action_price:
  enabled: true  # Работает только при use_testnet: false
  
  # Расписание
  execution_timeframes: ["15m", "1h"]  # Запуск только на закрытии этих ТФ
  zone_recalc_schedule:
    daily: "00:00"  # UTC - пересчёт зон 1D
    update_4h: true  # Обновление на каждом 4H закрытии
  
  # Зоны S/R
  zones:
    lookback_days: 90
    fractal_k_1d: 2
    fractal_k_4h: 2
    impulse_bars_check: 3  # Проверка импульса после базы
    impulse_atr_mult: 2.0  # Минимум 2×mTR(1D) для зоны
    zone_width_mult: 0.5  # zone_width = max(0.5×mTR, 0.15% price)
    zone_width_min_pct: 0.15  # Минимум 0.15% от цены
    buffer_mult: 0.25  # buffer для расширения зон
    merge_distance_mult: 0.75  # Слияние если центры ближе 0.75×mTR
    max_width_mult: 1.25  # max final_width = 1.25× базовой ширины
    top_zones_count: 6  # Топ-N зон для торговли
    broken_closes: 3  # Зона ломается после N закрытий за границей
  
  # Anchored VWAP
  avwap:
    # Таймфреймы для якорей
    anchor_15m_primary: "1h"
    anchor_15m_secondary: "4h"
    anchor_1h_primary: "4h"
    anchor_1h_secondary: "1d"
    
    # Параметры свингов
    fractal_k_1h: 3
    fractal_k_4h: 2
    impulse_mult: 1.5  # impulse >= 1.5×mTR для якоря
    impulse_bars_1h: 12  # L баров для проверки импульса
    impulse_bars_4h: 10
    
    # Sticky логика
    lock_bars_1h: 8  # Гистерезис после установки
    lock_bars_4h: 4
    ttl_bars_1h: 60  # ~2.5 суток
    ttl_bars_4h: 30  # ~5 суток
    
    # Переякоривание
    structure_break_closes: 3  # Для 1H
    structure_break_closes_4h: 2  # Для 4H
    structure_distance_mult: 0.25  # >= 0.25×mTR от AVWAP
    
    # Конфлюэнс
    confluence_tolerance_mult: 0.5  # Цена в пределах 0.5×mTR(1H) от AVWAP
  
  # EMA фильтры
  ema:
    periods: [50, 200]
    timeframes: ["4h", "1h"]
    strict_mode: true  # Строгая проверка по обоим ТФ
    aggressive_mode: false  # Разрешить при конфликте 4H/1H
  
  # Паттерны
  patterns:
    enabled: ["pin_bar", "engulfing", "inside_bar", "fakey", "ppr"]
    eps_mult: 0.0001  # eps = 0.0001 × price
    
    # Pin-Bar
    pin_bar:
      wick_body_ratio: 2.0  # wick >= 2×body
      wick_range_ratio: 0.6  # wick >= 0.6×range
      opposite_wick_max: 0.25  # upper_wick <= 0.25×range
      close_position: 0.6  # close >= (low + 0.6×range)
    
    # Engulfing
    engulfing:
      body_ratio: 0.8  # body >= 0.8× prev body
    
    # Fakey
    fakey:
      sequence_bars: 3  # mother, inside, breakout
  
  # Входы и управление
  entry:
    buffer_atr_mult: 0.25  # buffer = max(0.25×mTR, 0.05% price)
    buffer_min_pct: 0.05
    
    tp1_rr: 1.0  # TP1 = 1R
    tp2_rr: 2.0  # TP2 = 2R или ближайшая зона
    partial_tp1: 0.5  # 50% на TP1
    partial_tp2: 0.5  # 50% на TP2
    
    min_rr_zone: 1.0  # Минимум 1R до противоположной зоны
    breakeven_rr: 1.0  # BE после 1R
  
  # Anti-duplicates
  cooldown:
    timeframe_1h: 6  # часов
    timeframe_15m: 2  # часов
    unique_key: ["symbol", "direction", "zone_id", "pattern", "timeframe"]
  
  # Производительность
  performance:
    track_partial_exits: true  # Отслеживать частичные фиксации
    separate_stats: true  # Отдельная статистика от основных стратегий
